#!/usr/bin/env python2.6

import humdrum

if __name__ == "__main__":
    #f = humdrum.parse_file("/home/kroger/Documents/xenophilus/data/k160-02.krn")
    f = humdrum.parse_file("/home/kroger/Documents/xenophilus/data/test.krn")
    for item in f.data:
        print(item)
